apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dp
  labels:
    name: backend-app
    type: backend
spec:
  template:
    metadata:
      name: backend-pod
      labels:
        app: backend-app
        type: backend
    spec:
      containers:
        - name: nginx-backend
          image: nginx
  selector:
    matchLabels:
      type: backend
  replicas: 2
