apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-dp
  labels:
    name: redis-app
    type: database-redis
spec:
  template:
    metadata:
      name: redis-pod
      labels:
        app: redis-app
        type: database-redis
    spec:
      containers:
        - name: redis
          image: redis
  selector:
    matchLabels:
      app: redis-app
  replicas: 1
    