apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql-server
spec:
  containers:
    - name: mysql-container
      image: mysql:8
      env: 
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: spira